package servent.message;

public enum MessageType {
	TRANSACTION, LY_MARKER, TREE_ACCEPT, TREE_REJECT, TREE_QUERY, TREE_BORDER_REJECT, FOUND_REGION, LY_COLLECTED_RESULTS, LY_REGION_TRANSACTION, LY_BLANK_STATUS, TREE_RESET, TREE_RESET_CONFIRM, LY_TELL
}
